### ISSUE TITLE
Can't progress to unlocked ballot

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#151] opened 2024-09-20 17:15 UTC
I have yet to progress all the way to the ballot step, because during scoring I keep getting blocked by an application error.

<img width="1102" alt="Screenshot 2024-09-20 at 10 04 09 AM" src="https://github.com/user-attachments/assets/c9082ea2-165e-4b72-a588-2e74a9618fa5">

**Comment by meglister** [comment] 2024-09-20 18:08
Adding more context!

To repro:
- Load https://develop-op-voting.up.railway.app/project/0xb0913f628928698951760223a5691480a8f63b4545b5177490959b8966330272
- Make sure you are signed in w badgeholder/allowlisted address
- Observe the following error in the console (attached)
![Screenshot 2024-09-20 at 2 07 26 PM](https://github.com/user-attachments/assets/3866bfdc-76e0-4bed-9145-7829c596668f)

Based on a version of the page that flashed briefly before showing an error, I think it is an API issue bc there are no team members available. Pls reproduce and verify (or fix!)

**Comment by meglister** [comment] 2024-09-20 18:11
This is a dupe of #144

**Closed as completed** 2024-09-22 05:13 UTC
