### ISSUE TITLE
Showing NaN under npm package for Account Abstraction - ERC-4337 Team

### ISSUE THREAD

**Issue by Sednaoui** [grants-stack-frontier/op-rf4-voting-ui#247] opened 2024-09-27 08:44 UTC
### What was the URL where the error occurred?

https://round5.optimism.io/project/0x5f8e06ced087848712b56730976a7a31f3fbd14a862a75174d6e7fc56eebc627

I noticed it happened also for another application: 

https://round5.optimism.io/project/0x89d1fdde640450d31363f3b225210cf7472f1376f5481f644b214a5725b6e6b5

### What happened?

The metrics are not displayed properly. I believe it's because the input expect is a github URL and not an npm url. 

![image](https://github.com/user-attachments/assets/e9d7c428-e917-4dd6-87fc-947259db0b7a)

### What should have happened instead?

The tab should display the metrics properly 

### Steps to Reproduce

1. Open the ERC-4337 Team page
2. Scroll down and click on the npm package under Repos, links and contracts

### What browser(s) are you seeing the problem on?

Firefox

**Comment by vidvidvid** [comment] 2024-09-27 10:35
duplicate of #244

**Closed as completed by vidvidvid** 2024-09-27 10:35 UTC
Labels: bug
