### ISSUE TITLE
Ballot: Rounding numbers

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#230] opened 2024-09-26 17:16 UTC
(couldn't find a previous issue)

The allocation percentage numbers should be rounded to the first decimal. Currently you get a very long number (e.g. "9.361842105263159")
<img width="1100" alt="Screenshot 2024-09-26 at 19 15 52" src="https://github.com/user-attachments/assets/eb17e268-1837-450e-b806-631410e12cb0">

**Comment by geovgy** [comment] 2024-09-26 19:18
Closing this issue since its a duplicate of #181

**Closed as completed by geovgy** 2024-09-26 19:18 UTC
