### ISSUE TITLE
Editing budget percentages isn't working properly

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#96] opened 2024-09-17 21:39 UTC
Here's how the auto-weight functionality is meant to work: 

1. Categories are automatically weighted when added to the ballot - adding up to 100%.
2. Anytime a user edits a category percentage by input, plus, or minus (or clicks the open-lock icon), that category input is “locked”. The icon-button should visually switch to the locked state. That category's percentage can still be adjusted up and down.
3. Non-locked metrics in the list (any metric that hasn't been edited) are then automatically balanced across the remaining percent.
4. When a locked metric is unlocked (by clicking the lock icon), it re-enters the non-locked pool of metrics and is auto-balanced across the remaining percent.

Currently, it doesn't appear to be working like this, or the lag between save times is making it feel broken. [Here's a screen-by-screen from Round 4 Voting that may be helpful.](https://www.figma.com/design/1j0mOMlZWtve4GK5kF0WQU?node-id=2942-123034#837542774)

Here's a screencast: 
[Sep-17-2024 14-32-23.mp4.zip](https://github.com/user-attachments/files/17035215/Sep-17-2024.14-32-23.mp4.zip)

**Comment by meglister** [comment] 2024-09-17 21:40
Believe this is a dupe of #91

**Comment by shaunop** [comment] 2024-09-17 21:43
Yep! Thanks, I'll add my comments into yours.

**Comment by vidvidvid** [comment] 2024-09-18 00:13
duplicate, closing

**Closed as completed by vidvidvid** 2024-09-18 00:13 UTC
