### ISSUE TITLE
Project Ordering hickups

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#128] opened 2024-09-19 10:49 UTC
The ordering of projects is a bit buggy and feels off. Sometimes it allows me to order the project and sometimes it doesnt. @shaunop is this the intended design of this? It took me a minute to understand that I need to hit the ordering boxes when ordering

https://github.com/user-attachments/assets/23bc7464-529f-4dd2-9447-0e878d28d1f1

**Comment by miguellords** [comment] 2024-09-19 10:50
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by meglister** [comment] 2024-09-19 13:56
Noting that I experienced this but was not able to consistently reproduce

**Comment by shaunop** [comment] 2024-09-19 15:46
Here's the intended pattern for the ballot list ordering.

If a user is in custom mode:

1. If the user manually edits any of the amount-inputs [ex: 120,000 OP] in the list, then the allocation method switches to "Custom"
2. The list will always be ordered 1, 2, 3, 4 ... from top to bottom, with number-1 being the project with highest allocation.
3. So, if a user manually edits the amount-input for a project, then that project will be repositioned in the list automatically. 

If a user has a preset allocation method selected (like Impact groups, top-to-bottom, etc):

1. When a user reorders the list, either by editing the [1] [2] [3] or dragging a project up and down the list, then the amount-input will adjust based on the place in the list.

I'm available for a call if helpful.

**Comment by geovgy** [comment] 2024-09-20 04:52
> 1. If the user manually edits any of the amount-inputs [ex: 120,000 OP] in the list, then the allocation method switches to "Custom"

This is included in PR #120.

> 2. The list will always be ordered 1, 2, 3, 4 ... from top to bottom, with number-1 being the project with highest allocation.
> 3. So, if a user manually edits the amount-input for a project, then that project will be repositioned in the list automatically.

2 is TBD (solely going by position from API atm). For 3, do you want the project to reposition as soon as the user unfocuses out of the allocation input?

> It took me a minute to understand that I need to hit the ordering boxes when ordering

I can make the entire project row clickable to start dragging if preferred. @shaunop was that the idea or do you want to require holding the hamburger icon specifically to start dragging (ordering) the projects? I'm still unclear on that part.

**Comment by shaunop** [comment] 2024-09-20 16:20
> For 3, do you want the project to reposition as soon as the user unfocuses out of the allocation input?

Yes, that's how it should work.

> I can make the entire project row clickable to start dragging if preferred.

As long as we retain the ability to click into project details, then yes we can make the whole list item draggable. The button is an indicator that projects can move up and down, so let's keep that in play too (yes, you'd click and hold the drag button to move up and down).

**Comment by geovgy** [comment] 2024-09-22 21:00
Hey @shaunop once this PR is merged, I would love to get your feedback on the auto-sorting after inputting a custom allocation amount. 

Atm the allocation is saved `onBlur` (after clicking or tabbing out of the input field) and then there is a slight latency from pinging the API and refreshing the list. Wondering if you think it would be a good idea to include a spinner next to the input during that.

**Closed as completed** 2024-09-22 23:36 UTC
Labels: in review

**Comment by shaunop** [comment] 2024-09-23 19:04
Hey @geovgy the auto-sort looks good. However we also need to disable the drag-to-reorder when in custom mode to avoid this https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/187
