### ISSUE TITLE
Unable to view projects after unlocking ballot

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#206] opened 2024-09-25 10:03 UTC
I've unlocked my ballot, when trying to view a project I get shown the unlock ballot prompt, which blocks me from viewing the project page

To repro: 
1. Unlock Ballot
2. View a project
<img width="1512" alt="Screenshot 2024-09-25 at 12 03 02" src="https://github.com/user-attachments/assets/e876f9f5-e168-4c52-a98d-73a010e4c5f4">

**Comment by vidvidvid** [comment] 2024-09-25 15:56
@JSeiferth seems like a duplicate of https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/179 ?

**Comment by JSeiferth** [comment] 2024-09-25 18:08
> @JSeiferth seems like a duplicate of #179 ?

These are different things; https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/179 asks me to unlock my ballot before I rated a single project. This issue prevents me from seeing a project, because of the unlock banner, after I have already rated all the projects

**Closed as completed** 2024-09-26 08:32 UTC

**Comment by JSeiferth** [comment] 2024-09-27 08:31
@vidvidvid I still experience this issue

https://github.com/user-attachments/assets/7c878a4f-346a-41f9-899a-1e203b07d161

**Comment by vidvidvid** [comment] 2024-09-27 09:43
@JSeiferth some unwanted code got into the dev branch yesterday. it should be fixed now.
