### ISSUE TITLE
Ballot: Text "OP calculations in this ballot are based on your category budget of 0 OP."

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#209] opened 2024-09-25 10:15 UTC
The text, "OP calculations in this ballot are based on [your category budget of 0 OP" is not accurate. This seems to be an issue when you first unlock your ballot. After I refreshed the page it displayed the correct value

<img width="1116" alt="Screenshot 2024-09-25 at 12 13 17" src="https://github.com/user-attachments/assets/06310a79-92b7-47c0-b0f7-bdabeabef6dc">
<img width="768" alt="Screenshot 2024-09-25 at 12 13 51" src="https://github.com/user-attachments/assets/6343d401-1a55-42d8-accf-dfcd61cc9926">

**Comment by vidvidvid** [comment] 2024-09-25 15:54
duplicate of #180 thank you for the additional info!

**Closed as completed by vidvidvid** 2024-09-25 15:54 UTC
