### ISSUE TITLE
Pairwise upload issue

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#138] opened 2024-09-19 18:08 UTC
From Pairwise team, please reach out to MoeNick on slack for more info.

So, our QA can successfully upload her ballot from Pairwise via Agora's API.
This is the payload she uses: 
[Flow_ballot-1726654235487.json](https://github.com/user-attachments/files/17063959/Flow_ballot-1726654235487.json)

This is the response we get when trying to retrieve our ballot using Agora's API 
[agora_ballot_GET-1726654349056.json](https://github.com/user-attachments/files/17063958/agora_ballot_GET-1726654349056.json)
 

These two almost perfectly match except for a couple of projects having null allocations in the API response while we send allocation: 0 from Pairwise.

However, when she goes to https://develop-op-voting.up.railway.app/ballot to see her ballot in this UI, she faces "Application error: a client-side exception has occurred"

This is her token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIweDk1OGU2QWFhQ2ZEZWE4MDJENzBlODZkODIwMjU5RjBhOTcwQkE2YTgiLCJzY29wZSI6InJlYWRlcjpwdWJsaWM7cmYtZGVtby11c2VyO2NhdGVnb3J5OmV0aGVyZXVtX2NvcmVfY29udHJpYnV0aW9ucyIsImlzQmFkZ2Vob2xkZXIiOmZhbHNlLCJjYXRlZ29yeSI6IkVUSEVSRVVNX0NPUkVfQ09OVFJJQlVUSU9OUyIsInNpd2UiOnsiYWRkcmVzcyI6IjB4OTU4ZTZBYWFDZkRlYTgwMkQ3MGU4NmQ4MjAyNTlGMGE5NzBCQTZhOCIsImNoYWluSWQiOiIxMCIsIm5vbmNlIjoicXE1UXB0U1ZuZjFtR2RweXgifSwiZXhwIjoxNzI2NzM4MDE5LCJpYXQiOjE3MjY2NTE2MTksIm5iZiI6MTcyNjY1MTYxOX0.g2AGiRyPSeJljFulr1rGTw-IDWiz9ZFhRx8rVdNRZec"

**Comment by vidvidvid** [comment] 2024-09-20 00:21
@meglister is it possible to provide more info? please open the console and paste any error messages from there. also there might be an error response in the network tab. please check the response tab of the query that was red (if any). 
attaching pictures for reference:
![Screenshot 2024-09-20 at 09 20 58](https://github.com/user-attachments/assets/658d68f0-6ff3-4a3d-89cc-e15928c4254c)
![Screenshot 2024-09-20 at 09 20 19](https://github.com/user-attachments/assets/952278c2-1d09-4ef0-8460-3d3e23ca0643)

**Comment by vidvidvid** [comment] 2024-09-20 07:27
@geovgy link of the slack conversation for reference https://weetopolgmail-b5p9646.slack.com/archives/C06S2B5CM36/p1726675081605039

**Comment by geovgy** [comment] 2024-09-21 21:21
I took a guess on the reason for the client-side error could be from not handling null types well in the ballot page. Not completely positive it fixed things though. The QA tester from Pairwise would need to try again and let us know.

**Comment by geovgy** [comment] 2024-09-22 21:58
This issue does not seem to be replicable after more testing from both the QA tester and myself. The cause of the issue is still a mystery. Maybe it was fixed, maybe not. I'm keeping this open for now to put it on watch just in case. We can probably close it soon though.

**Comment by MoeNick** [comment] 2024-09-23 12:37
Im not sure if this issue is in the right place or not, the mystery that @geovgy is talking about may be related to the CORS error. 

Would you please add `*.pairwise.vote` and `https://pairwise-rpgf5.vercel.app`/ to the CORS whitelist? it will solve some of these errors.

**Comment by MoeNick** [comment] 2024-09-26 13:14
A gentle reminder of the CORS issue. 
@meglister @vidvidvid we still have limitations.

**Comment by geovgy** [comment] 2024-09-26 17:40
Hey @MoeNick, from what I tested with Pairwise, you guys are only calling the Agora API and not us directly, correct? The QA was able to replicate the issue again?

**Comment by vidvidvid** [comment] 2024-09-28 11:34
@MoeNick @geovgy what's the status on this?

**Comment by geovgy** [comment] 2024-09-29 18:44
This issue seems good to close now.

**Closed as completed** 2024-09-30 01:41 UTC
Labels: in review
