### ISSUE TITLE
Even if I've unlocked my ballot, I should be able to revisit project detail views

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#219] opened 2024-09-25 16:18 UTC
Even if I've unlocked my ballot, I should be able to revisit  project detail views. Currently, if I try to revisit a project detail view, I see the unlock ballot modal and then am landed back in the ballot page. 

Current:
https://github.com/user-attachments/assets/88ec21ce-6714-49ff-a245-2e2a6af8b50b

**Comment by nitegeist** [comment] 2024-09-25 16:47
Duplicate of #206. I'm on it

**Closed as completed** 2024-09-26 07:56 UTC
