### ISSUE TITLE
# of projects scored is greater than total available

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#257] opened 2024-09-27 16:44 UTC
### What was the URL where the error occurred?

https://develop-op-voting.up.railway.app/project/0x036fc6760516760a635745917887ae8539ec512f4fde7fd4705a0f3bf3d0cb60

### What happened?

1. I navigated to project scorig
2. I started with 0 projects scored and then scored 2 projects
3. Though my total number of projects scored is 2, I observed the dialogue telling me I had scored 40 out of 29 available projects

![Screenshot 2024-09-27 at 12 42 43 PM](https://github.com/user-attachments/assets/cb426c79-328e-436a-9125-259b1204ab07)

### What should have happened instead?

Should have displayed 2 out of 29 projects vs 40 out of 29

### Steps to Reproduce

See above

**Comment by JSeiferth** [comment] 2024-09-27 17:13
I had the same issue. Was right after API data was changed, so prob related

**Comment by nitegeist** [comment] 2024-09-28 00:58
This was most likely due to the API data change. I've tried to reproduce this issue with a fresh address and didn't get this problem. Keeping it open in case it reappears though.

**Comment by vidvidvid** [comment] 2024-09-28 11:35
@meglister @JSeiferth does this still happen for you? if so, does clearing the cache solve the problem?

**Comment by JSeiferth** [comment] 2024-09-30 20:02
This issue is back 

https://github.com/user-attachments/assets/c027b246-da31-4b4d-abc1-b5b194c2224d

**Comment by JSeiferth** [comment] 2024-09-30 20:10
Also gets into weird cycles of reviewing the same project and not being able to progress to the next one. 

https://github.com/user-attachments/assets/82e9a722-6d37-4e26-808b-48369202f1cd

**Comment by nitegeist** [comment] 2024-10-01 13:51
@JSeiferth the issues you're noticing should have been resolved with PRs #290 & #291. Can you re-test to ensure this is the case? I went through this flow with a wallet that I've already voted on all the projects with and also a new wallet to test the scoring flow and I haven't encountered these issues. They have been confirmed fixed by @meglister

**Closed as completed** 2024-10-01 15:43 UTC
Labels: bug, in review
