### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#144] opened 2024-09-20 12:21 UTC
Went into rating projects. Had skipped a few projects and was about 30/50 projects. After Rating a project, see "Application error: a client-side exception has occurred (see the browser console for more information)." error. On [this project](https://develop-op-voting.up.railway.app/project/0xb0913f628928698951760223a5691480a8f63b4545b5177490959b8966330272). 
<img width="1512" alt="Screenshot 2024-09-20 at 14 20 22" src="https://github.com/user-attachments/assets/d8494b93-a174-4d68-aed4-17e408014374">

Refreshing does not help. I had to navigate back to the homepage of the voting app and click back into rating projects, where I was then shown a different project

**Comment by JSeiferth** [comment] 2024-09-20 12:24
Seems to be an issue with viewing this project https://develop-op-voting.up.railway.app/project/0xb0913f628928698951760223a5691480a8f63b4545b5177490959b8966330272

**Comment by meglister** [comment] 2024-09-20 18:11
This is a dupe of #151

**Comment by vidvidvid** [comment] 2024-09-21 01:28
closing as a duplicate of #151

**Closed as completed** 2024-09-21 01:28 UTC
