### ISSUE TITLE
Ballot submit blocker: Doesn't update with ballot state

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#129] opened 2024-09-19 10:55 UTC
Add percentages to projects in ballot. See error message of having to remove 10%. Remove 10%. Still same error message. 

https://github.com/user-attachments/assets/a10681da-340d-4978-acea-3b99dd8ae3b8

**Comment by meglister** [comment] 2024-09-19 13:55
oops, I created a dupe of this -- #130

**Closed as completed** 2024-09-20 00:07 UTC
